### ISSUE TITLE
read the FW version not corrcet in MST 4.16 version on MSB7790

### ISSUE THREAD

**Issue by 824380210** [stanford-rc/ibswinfo#7]
hi ,Sir
    I have update the MFT version to 4.16.and it looks tha the FW version is not correctly show in the output 

see the code change to work in 4.16
[root@n1041 ~]# diff myibcheck ibswinfo.sh
237c237
< [[ $mft_cur =~ 4\.16 ]] && add_idx="slot_index=0x0" || add_idx=""
---
> [[ $mft_cur =~ 4\.15 ]] && add_idx="slot_index=0x0" || add_idx=""

and the result ,highlight line with ====================

[root@n1041 ~]# ./myibcheck -d lid-0x00009 -o inventory
node_desription    : SwitchIB Mellanox Technologies
part_number        : MSB7790-ES2R
serial             : MT1520X02370
fw_version         : 0.0000.0000    ====================
psu0.serial        : MT151 =====================

[root@n1041 ~]# flint -d  lid-0x00047 q
Image type:            FS3
FW ISSU Version:       1
FW Version:            15.2008.2402
FW Release Date:       12.2.2021
Description:           UID                GuidsNumber

[root@n1041 ~]# flint -d  lid-0x00009 q
Image type:            FS3
FW ISSU Version:       1
FW Version:            11.2008.2402   ====================
FW Release Date:       12.2.2021
Description:           UID                GuidsNumber  Step

**Comment by kcgthb** [comment]
Hi @824380210 
You're correct: with MFT 4.16, the MGIR register only reports 0s in place of the firmware version values:
```
# mlxreg -d lid-15 --reg_name MGIR --get | grep -E "extended_(major|(sub_)?minor)"
extended_major                  | 0x00000000
extended_minor                  | 0x00000000
extended_sub_minor              | 0x00000000
```
I'm afraid that's a problem with MFT 4.16 :\

**Comment by sjtbham** [comment]
We noticed similar issues with the PSU registers and were working round this by using the binary from the older 4.15 rpm. We have a ticket open with Mellanox this is supposed to be resolved with the 4.17 release of MFT.

**Comment by kcgthb** [comment]
Unfortunately, the recently released MFT 4.17 does not resolve the problem. 
I have a case open with Mellanox about this as well.

**Comment by kcgthb** [comment]
From Mellanox support:
> Engineering Team informed that the fix will be implemented in upcoming MFT 4.17.2 version, tentatively scheduled for release in August.

**Comment by kcgthb** [comment]
Well, it turns out that MFT 4.17.2 still doesn't fix that issue, so it's still pending. Mellanox engineering is still working on a fix.

**Comment by kcgthb** [comment]
MFT 4.18 does finally fix this issue, and can be downloaded at https://www.mellanox.com/products/adapter-software/firmware-tools
[Version 0.4](https://github.com/stanford-rc/ibswinfo/releases/tag/0.4) now requires MFT 4.18.
