### ISSUE TITLE
mft-4.15.1-100.x86_64 and slot_index=0x0

### ISSUE THREAD

**Issue by kramanella** [stanford-rc/ibswinfo#9]
After update to RHEL7.9 mft package changed from mft-4.14.0-105.x86_64 to mft-4.15.1-100.x86_64 and began seeing, 
`error:  Index: slot_index was not provided`

Added slot_index=0x0 to MTMP and MTCAP as workaround and it's working fine, we call the script with only -d dev. 

diff of our local copy and the original with the changes,
```
diff /usr/local/sbin/ibswinfo.sh ibswinfo-master/ibswinfo.sh
227,228c227
< rid[MTMP]="sensor_index=0x0,slot_index=0x0"
< rid[MTCAP]="slot_index=0x0"
---
> rid[MTMP]="sensor_index=0x0"
```

**Comment by kcgthb** [comment]
Hi @kramanella 

Yes, support for MFT 4.15 has been added in 8daf45a316a391f8c7f3b14122ba23959e8f5a94, the current version from the `default` branch should work. I'll make a new release once MFT 4.17.2 is released, which should fix #7 as well.

**Comment by kcgthb** [comment]
Well, it turns out that MFT 4.17.2 still doesn't fix that issue, so it's still pending. Mellanox engineering is still working on a fix.

**Comment by kcgthb** [comment]
MFT 4.18 does finally fix this issue, and can be downloaded at https://www.mellanox.com/products/adapter-software/firmware-tools
[Version 0.4](https://github.com/stanford-rc/ibswinfo/releases/tag/0.4) now requires MFT 4.18.
